### ISSUE TITLE
Move System.Device.Gpio to use the new Api Surface

### ISSUE THREAD

**Issue by joperezr** [dotnet/iot#16]
This issue is going to track the work of moving the implementation of System.Device.Gpio to the Api surface that we are intending to ship. It also includes cleaning up the code and productizing it.
The steps to complete this are:

- [x] Port the enums and Controller code into the new Api shape. (Done in #20)
- [x] Port the Unix Portable/Generic Driver (Done in #23 and #45)
- [x] Port the Unix Raspberry Pi Optimized Driver
~~- [ ] Port the Unix Hummingboard Optimized Driver~~ Not required for V1 any longer.
- [x] Port Spi classes (Done in #53)
- [x] Port I2C classes (Done in #51)

**Comment by krwq** [comment]
@joperezr what's the status on this?

**Comment by joperezr** [comment]
The one outlined above is still acurate as we haven't ported the Hummingboard driver implementation yet. It is on the backlog but I was waiting to see how viable is it to use libgpiod, since if that is a good answer then perhaps we won't need to port that any longer.

**Comment by joperezr** [comment]
This is done now as Hummingboard driver is not essential for V1 given we now have the libgpiod implementation.
