### ISSUE TITLE
Create a Microchip MCP23XXX binding

### ISSUE THREAD

**Issue by shaggygi** [dotnet/iot#88]
Create a binding API for the Microchip MCP23XXX family.

//cc @joperezr @joshfree Please assign this to me.  I have a prototype, but trying to work out the kinks and such.  This has been a good exercise as it has bought up a few issues/questions.  I will post more details and action items as progress is made.  Thx

### Possible Iterations
- [x] (#91) Create initial Mcp23xxx project with tests and samples.
- [x] (#130) Separate with Mcp23xxx abstract, create Mcp230xx (I2C), create Mcp23Sxx (SPI).
- [x] (#130) Add additional pins for reset and interrupt lines.
- [x] (#130) Add ReadBit/WriteBit helper methods.

**Comment by shaggygi** [comment]
See initial PR https://github.com/dotnet/iot/pull/91

**Comment by shaggygi** [comment]
@joperezr @joshfree Would it be possible to go ahead and check-in https://github.com/dotnet/iot/pull/91?  This issue can continue to stay open, though.

This currently works for SPI and has some goodness for a starting layout on binding docs.

I've been thinking about binding fundamentals and understand this will change in future.  For example, similar to the Mcp2008 binding and implementing https://github.com/dotnet/iot/issues/90, I could see where I/O expanders could implement a similar format.  I'm not sure if this would be a [type of bus provider](https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/busproviders), but warrants more thoughts before getting too deep in developing more bindings.

Thx

**Comment by joperezr** [comment]
@shaggygi I left some feedback on the PR and it looks like you haven't had the chance yet to address/respond to it. Would you mind taking a look?
